### PR TITLE
fixed getting token and author id

### PR DESCRIPTION
**Pull request by titushm**

### CODE REVIEW

**Comment by abbydiode** [comment]
Hi! Thanks for your PR! I've noticed you've opened 3 PRs over the last 6 hours. Is there anything you need help with regarding your PRs? This one looks like a good improvement over the other two. I also wanted to let you know that the author of this repository is currently not very active and it might take a while to have your PR merged!

**Comment by titushm** [comment]
> 

Hi, yea you can ignore the previous two, I found issues with my method every time after I had sent a pr. I believe this should be final and wont need any more tweaking. anyway thanks for the reply!

**Comment by abbydiode** [comment]
For future reference, it's not necessary to close and open new PRs. You can [rebase](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History) commits to "undo", "redo", or edit commits that you've already pushed. Most users prefer PRs with few commits so this can be useful to squash multiple commits into one as well.

**Comment by victornpb** [comment]
Hi, can you explain what this code does? I just tested the current implementation, and it is not broken. It's been reliable for quite some time.

**Comment by Aida-Enna** [comment]
+1 for current code working

**Comment by victornpb** [comment]
I tested this and it works, I will keep this in case the current implementation stops working.

**Comment by titushm** [comment]
I'm not sure exactly when it causes the error but I think if you open up Dev tools and look at the localstorage then it seems to hide the token from the localstorage

**Comment by titushm** [comment]
I will test later

**Comment by victornpb** [comment]
> I'm not sure exactly when it causes the error but I think if you open up Dev tools and look at the localstorage then it seems to hide the token from the localstorage

Yes, that's right, my implementation fails if you open devTools. It seems that they recently added code to prevent people from running scripts directly in the console which makes sense.

I'm not entirely sure how they are able to detect devTools open TBH, but even tho it's kinda annoying when I'm trying to debug undiscord, I think its better to keep as is because the chance of it stopping working is smaller.

your method of injecting a module in the webpack runtime is clever ngl.

**Comment by victornpb** [comment]
> Does it detect the size of the discord window? If you set devtools to be a separate window can it still detect it?

Yes, you are correct, it works if you detach the devTools window.

So they are probably doing something like:
```js
// on window resize
isDevToolsOpen = ((window.outerWidth - window.innerWidth) + (window.outerHeight - window.innerHeight)) > 500;
    
if (isDevToolsOpen) delete localStorage;
```

**Comment by TheRedstoneRadiant** [comment]
Can this please be merged?

I use the copy/paste version very often and have to manually get the token via network requests each time.

**Comment by titushm** [comment]
> Can this please be merged?
> 
> I use the copy/paste version very often and have to manually get the token via network requests each time.

It was merged at one point but was reverted as to maintain parity with getting the user id / not enough people had an issue with the old system

**Comment by titushm** [comment]
I have the working version on my GitHub https://github.com/titushm/undiscord-patched

**Comment by AtariDreams** [comment]
Any updates on this?

**Comment by titushm** [comment]
> Any updates on this?

The owner of this repo is not very active so might take a while if a pull request was to happen

**Pull request merged**
