### PR TITLE
Ended because API returned an empty page (Fix)

### PR DESCRIPTION
**Pull request by overdosing**
Fixes the problem regarding API returning an empty page

Summary - Since everything is done in chunks of 25, if the system finds 1-25 messages it will delete them. If it finds 0 messages (but total-offset>0) it will increment the offset by 25 to skip the 25 non-deletable messages and recurse. If (total-offset <= 0) then it will still end.

Incrementing the offset by 1 each time is not ideal because you'll still be traversing huge chunks of dead messages.

I had the original problem described above earlier - I've been running this for several hours now and have deleted thousands of messages with no errors and no API-induced slowdowns.

Credit: PinkyLaRue & larryqiann

---
This change is [Reviewable](https://reviewable.io/reviews/victornpb/deletediscordmessages/218)

### CODE REVIEW

**Comment by sintrix** [comment]
funny, i just forked this to write a similar fix for the same issue. merge pl0x!

**Comment by Wade-BAV** [comment]
Is there a hope that this is fixed?

**Comment by Assistancepls** [comment]
I have the same problem and I have about 30,000 messages left to delete. Is this still being worked on?

**Review by JimmyRecardFr — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/victornpb/deletediscordmessages/218)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @overdosing)

**Comment by Wayyllon** [comment]
I had this issue just now, reinstalled it & it still seemed bugged, a workaround for this is to set it to **delete all messages prior to the one you started having issues with & it'll function just fine.**

**Comment by aijorgenson** [comment]
This fix may be a bit overkill, please see PR #323

**Comment by bugsnitch** [comment]
now how to fix this nothing seems to be working

**Pull request closed without merging**
