### PR TITLE
patch: skip archived messages after one attempt

### PR DESCRIPTION
**Pull request by ckcr4lyf**
Currently, archived threads are a big problem: We fail to delete messages in an archived thread. This itself could be seen as a problem, but the bigger problem (IMO), is that these messages *keep coming up* when searching new pages, since they are still returned by the search call! This is a major problem when the number of archived messages hits 25, since a new page will return all archived messages, and no progress can be made.

This MR implements a kind of patch - if we fail to delete a message, and the reason is that the thread is **archived** , then we increment the offset. 

This allows the fetch of the next page to skip these archived messages from the search results, allowing the overall deletion to make further progress.

### Other MRs

https://github.com/victornpb/undiscord/pull/457 -> This hack fix doesn't help much, since the next search will yield these messages again.

https://github.com/victornpb/undiscord/pull/393 -> This is arguable more efficient, but has a lot of changes, so may take more time to review merge. In the meantime a patch to at least allow further progress on non-archived messages could be useful to some.

### CODE REVIEW

**Comment by ckcr4lyf** [comment]
Before: Notice how the next page gets the archived messages again... 

before_undiscord

After: Next page continues off of last deletion (thanks to increment on offset)

after_undiscord

**Comment by ckcr4lyf** [comment]
Seems there are conflicts, let me rebase

**Comment by ckcr4lyf** [comment]
FYI: RE: 2k changed lines on the compiled script, I just ran `npm run lint:fix` after merging latest master, I think #439 erroneously introduced those different line break stuffs

**Comment by victornpb** [comment]
thank you for your contribution, looks good to me. A more long term solution would be trying to filter out threads entirely, idk if thats possible tho

**Review by victornpb — APPROVED** [review]

**Comment by victornpb** [comment]
> FYI: RE: 2k changed lines on the compiled script, I just ran `npm run lint:fix` after merging latest master, I think #439 erroneously introduced those different line break stuffs

you are right, thank you

**Pull request merged**
